### ISSUE TITLE
Fazer tela de listagem de palestrantes

### ISSUE THREAD

**Issue by fdaciuk** [scdevsummit/sc-dev-summit-website#2]

**Comment by eminetto** [comment]
Poderíamos já colocar os dois palestrantes confirmados. O que acham? Seria o Aurélio e o Maujor

**Comment by fdaciuk** [comment]
Ainda não tem o front dessa parte, tem que fazer. Vou ver se consigo fazer isso final de semana.

**Comment by viniciusdacal** [comment]
@fdaciuk se tiver algo que eu possa ajudar, me da um toque :smile:

**Comment by fdaciuk** [comment]
@viniciusdacal te mandei email com o PSD dessa parte =)

**Comment by rafacianci** [comment]
Closed by #19

**Comment by fdaciuk** [comment]
@rafacianci, detalhe: coloca no config um parâmetro para mostrar essa área somente se houver palestrantes. Pode ser um `isShowTalks: false`, senão vai aparecer a sua foto e sua palestra "E o pé de feijão" quando fizer deploy :P

**Comment by rafacianci** [comment]
ahh blz.. é que eu já deixei comentado o include do partials/talks para que nao aconteca isso. Mas já crio essa config.. :D

**Comment by fdaciuk** [comment]
Então tá de boa.. não reparei que tava comentado xD
