### ISSUE TITLE
Parou de funcionar o build depois dos últimos PRs aprovados

### ISSUE THREAD

**Issue by eminetto** [scdevsummit/sc-dev-summit-website#20]
Ao atualizar o repositório no servidor e rodar o comando npm run deploy (ou o run build) acontece o seguinte erro:

> @ deploy /var/www/html/sc-dev-summit-website
> npm run build && surge --domain scdevsummit.surge.sh ./build
> 
> @ build /var/www/html/sc-dev-summit-website
> npm run lint && gulp build
> 
> @ lint /var/www/html/sc-dev-summit-website
> standard --verbose | snazzy

standard: Use JavaScript Standard Style (http://standardjs.com) 

/var/www/html/sc-dev-summit-website/src/scripts/map.js
  1:10  error  'initMap' is defined but never used        no-unused-vars
  1:17  error  Missing space before function parentheses  space-before-function-paren
  2:17  error  'google' is not defined                    no-undef
  5:13  error  Unexpected trailing comma                  comma-dangle
  6:5   error  Extra semicolon                            semi
  8:7   error  'marker' is defined but never used         no-unused-vars
  8:20  error  'google' is not defined                    no-undef

/var/www/html/sc-dev-summit-website/src/scripts/talks.js
   1:31  error  Missing space before function parentheses  space-before-function-paren
   1:33  error  Missing space before opening brace         space-before-blocks
   2:65  error  Extra semicolon                            semi
   5:57  error  Extra semicolon                            semi
   6:58  error  Extra semicolon                            semi
   7:58  error  Extra semicolon                            semi
   8:5   error  Extra semicolon                            semi
  10:25  error  Missing space before function parentheses  space-before-function-paren
  11:37  error  Extra semicolon                            semi
  12:46  error  Extra semicolon                            semi
  13:80  error  Extra semicolon                            semi
  16:55  error  Extra semicolon                            semi
  18:43  error  Extra semicolon                            semi
  20:5   error  Extra semicolon                            semi

✖ 21 problems

npm ERR! Linux 3.13.0-43-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "lint"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! @ lint: `standard --verbose | snazzy`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the @ lint script 'standard --verbose | snazzy'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     standard --verbose | snazzy
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/sc-dev-summit-website/npm-debug.log

npm ERR! Linux 3.13.0-43-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! @ build: `npm run lint && gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script 'npm run lint && gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint && gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/sc-dev-summit-website/npm-debug.log

npm ERR! Linux 3.13.0-43-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "deploy"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! @ deploy: `npm run build && surge --domain scdevsummit.surge.sh ./build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ deploy script 'npm run build && surge --domain scdevsummit.surge.sh ./build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && surge --domain scdevsummit.surge.sh ./build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/sc-dev-summit-website/npm-debug.log

Estava funcionando corretamente até semana passada

**Comment by eminetto** [comment]
@fdaciuk @viniciusdacal @rafacianci tem alguma ideia do que pode ser?

**Comment by fdaciuk** [comment]
É lint.. @viniciusdacal @rafacianci, tem que rodar `npm run lint` pra ver os problemas e ajustar isso. Esqueci de colocar no README, se puderem adicionar isso =)

**Comment by fdaciuk** [comment]
Acho que seria interessante integrar o travis, que ae a gente consegue ver isso antes de aprovar o PR xD

**Comment by viniciusdacal** [comment]
@eminetto corrijo isso assim que chegar em casa.
@fdaciuk o travis é uma boa mesmo.
