### ISSUE TITLE
Colocar logo da ConexTI como apoio

### ISSUE THREAD

**Issue by eminetto** [scdevsummit/sc-dev-summit-website#24]
Eles estão apoiando com a hospedagem do site

**Comment by eminetto** [comment]
Logo http://cl.ly/3v0H3f0q2W1E

**Comment by fdaciuk** [comment]
@eminetto consegue pegar com eles em SVG ou PNG transparente? Esse está em CDR :(

**Comment by eminetto** [comment]
http://cl.ly/3p1O320h3I2q

**Comment by eminetto** [comment]
@fdaciuk coloquei o link aqui :)
