### ISSUE TITLE
Adicionar todos os patrocinadores / apoiadores

### ISSUE THREAD

**Issue by fdaciuk** [scdevsummit/sc-dev-summit-website#8]

**Comment by eminetto** [comment]
Adicionar a Coderockr como apoiadora. @fdaciuk eu tenho o logo em .ai, png e psd. O que é melhor? SVG?

**Comment by fdaciuk** [comment]
SVG é melhor =)
Mas se tiver em PNG transparente, pode se tbem =)

**Comment by eminetto** [comment]
Segue o logo @fdaciuk 
![cdr - logo preto](https://cloud.githubusercontent.com/assets/197939/13633605/e270bbe6-e5ce-11e5-8232-4ae81fdcac78.png)

Se não der certo com esse arquivo me avisa que eu resolvo :)

**Comment by fdaciuk** [comment]
Foi! zo/
